### ISSUE TITLE
Error: Cannot find module 'connect-history-api-fallback'

### ISSUE THREAD

**Issue by itd** [FormidableLabs/formidable-react-starter#13]
Just thought I'd give it a whirl. Received this message:

```
kb:/web/js/formidable-react-starter
$ npm run dev

> formidable-react-app-starter@0.0.1 dev /web/js/formidable-react-starter
> node server/development.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'connect-history-api-fallback'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/web/js/formidable-react-starter/server/development.js:3:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! formidable-react-app-starter@0.0.1 dev: `node server/development.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formidable-react-app-starter@0.0.1 dev script 'node server/development.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formidable-react-app-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/development.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formidable-react-app-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formidable-react-app-starter
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /web/js/formidable-react-starter/npm-debug.log
 on master
```

**Comment by kenwheeler** [comment]
I'll check it out
